// Generated by CoffeeScript 1.7.1
(function() {
  var ciccio, condition, number, opposite;

  number = 42;

  opposite = true;

  condition = false;

  if (opposite) {
    number = -42;
  }

  if (condition) {
    number = 53;
  }

  ciccio = function() {};

  console.log(number);

  $('#placeholder').append("Ciao come stai");

}).call(this);
