// Generated by CoffeeScript 1.7.1
(function() {
  var number, opposite;

  number = 42;

  opposite = true;

  if (opposite) {
    number = -42;
  }

  if (condition) {
    number = 53;
  }

  console.log(number);

}).call(this);
